Repository alttabsoft/13-zodiac-signs, pull requests merged in 2024-02, with the labels that each got.

#16 [Feat] 큐브 회전 후 큐브의 정보 업데이트 기능 추가
  Assets/13-zodiac-sign/Scenes/CubeScene.unity
  Assets/13-zodiac-sign/Scripts/CubeScripts/CubeManager.cs
  Assets/13-zodiac-sign/Scripts/CubeScripts/CubeManager.cs.meta
  Assets/13-zodiac-sign/Scripts/CubeScripts/CustomEventArgs.cs
  Assets/13-zodiac-sign/Scripts/CubeScripts/CustomEventArgs.cs.meta
  Assets/13-zodiac-sign/Scripts/CubeScripts/ReadCube.cs
  Assets/13-zodiac-sign/Scripts/CubeScripts/RotateCube.cs
  Assets/13-zodiac-sign/Scripts/MonoSingleTon.cs
  Assets/13-zodiac-sign/Scripts/MonoSingleTon.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 🕹️ feature, 🎅🏻 Santa

#17 [Feat] 플레이어 평타, 점프, 피격 기능 추가 (#14)
  Assets/Scenes/Rubik_BattleScene.unity
  Assets/Scenes/Rubik_TempAsset/Scripts/CharacterJump.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/CharacterJump.cs.meta
  Assets/Scenes/Rubik_TempAsset/Scripts/CharacterMove.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/MobApproach.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/MobApproach.cs.meta
  Assets/Scenes/Rubik_TempAsset/Scripts/PlayerHit.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/PlayerHit.cs.meta
  ProjectSettings/TagManager.asset
Labels: 🕹️ feature, 🛌 Rubik

#20 [Fix] 플레이어 점프 이슈 해결
  Assets/Scenes/Rubik_TempAsset/Scripts/CharacterJump.cs
Labels: 🛠️ fix
