Repository alttabsoft/13-zodiac-signs, pull requests merged in 2024-03, with the labels that each got.

#30 [FEAT] 병합된 브랜치 태그 후 자동 삭제 기능 추가 GITHUB ACTION
  .github/workflows/github-actions-demo.yml
Labels: 🕹️ feature

#28 [FEAT] 캐릭터 그림자, 원거리 몬스터 공격, 점프 시 근거리 피격 안되게 하는 기능 추가
  Assets/Scenes/Rubik_BattleScene.unity
  Assets/Scenes/Rubik_TempAsset/Scripts/BulletStatus.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/BulletStatus.cs.meta
  Assets/Scenes/Rubik_TempAsset/Scripts/CharacterMove.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/LongRangeMobBehavior.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/LongRangeMobBehavior.cs.meta
  Assets/Scenes/Rubik_TempAsset/Scripts/MobApproach.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/PlayerHit.cs
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
Labels: 🕹️ feature, 🛌 Rubik

#35 [FIX] GITHUB ACTION 주 개발 브랜치 변수명 문제
  .github/workflows/github-actions-demo.yml
Labels: 🕹️ feature, 🐥 Kihyun

#37 [FEAT] 맵 크기 증가, 카메라 캐릭터 추적 (#36)
  Assets/Scenes/Rubik_BattleScene.unity
  Assets/Scenes/Rubik_TempAsset/Scripts/BattleCamController.cs
  Assets/Scenes/Rubik_TempAsset/Scripts/BattleCamController.cs.meta
Labels: 🕹️ feature, 🛌 Rubik

#40 [FIX] CubeSceneUI Null Exception 버그픽스
  Assets/13-zodiac-sign/Scenes/CubeScene.unity
  Assets/13-zodiac-sign/Scripts/UIScripts/CubeSceneUI.cs
  Assets/13-zodiac-sign/Scripts/UIScripts/CubeSceneUI.cs.meta
Labels: 🐞 bug, 🛠️ fix, 🐥 Kihyun
